import './globals.css'
import { Changa } from 'next/font/google'
import Navbar from './components/Navbar'

const changa = Changa({ subsets: ['latin'], weight: ["400"] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={changa.className}>
        <Navbar />
        {children}</body>
    </html>
  )
}
